const model = {
  //app
  curentPage: "game",
  colorToMove: "white",
  enPassantIndex: null,
  modal: "none",
  currentIndexOfWhiteKing: 32,
  whiteCheck: false,
  currentIndexOfBlackKing: 39,
  blackCheck: false,

  //inputs
  isPiecePrimed: false,
  blackColor: "#800000",
  whiteColor: "#ffffff",
  squareWithPieceToMove: null,

  //data
  legalMoveColor: "#808080",
  selecktedColor: "#6dc544",
  idLeters: ["a", "b", "c", "d", "e", "f", "g", "h"], // do i need these?
  idNumbers: ["1", "2", "3", "4", "5", "6", "7", "8"], // do i need these?
  board: [],
  promoteBlackImg: [
    "img/black queen.png",
    "img/black rook.png",
    "img/black bishop.png",
    "img/black horse.png",
  ],
  promoteWhiteImg: [
    "img/white queen.png",
    "img/white rook.png",
    "img/white bishop.png",
    "img/white horse.png",
  ],
  InPlayPieces: [
    {
      id: "black king e",
      type: "king",
      possison: "e8",
      color: "black",
      hasMoved: false,
      imageLink: "img/black king.png",
    },
    {
      id: "black queen d",
      type: "queen",
      possison: "d8",
      color: "black",
      imageLink: "img/black queen.png",
    },
    {
      id: "black bishop c",
      type: "bishop",
      possison: "c8",
      color: "black",
      imageLink: "img/black bishop.png",
    },
    {
      id: "black bishop f",
      type: "bishop",
      possison: "f8",
      color: "black",
      imageLink: "img/black bishop.png",
    },
    {
      id: "black knight b",
      type: "knight",
      possison: "b8",
      color: "black",
      imageLink: "img/black horse.png",
    },
    {
      id: "black knight g",
      type: "knight",
      possison: "g8",
      color: "black",
      imageLink: "img/black horse.png",
    },
    {
      id: "black rook a",
      type: "rook",
      possison: "a8",
      color: "black",
      hasMoved: false,
      imageLink: "img/black rook.png",
    },
    {
      id: "black rook h",
      type: "rook",
      possison: "h8",
      color: "black",
      hasMoved: false,
      imageLink: "img/black rook.png",
    },
    {
      id: "black pawn a",
      type: "pawn",
      possison: "a7",
      color: "black",
      hasMoved: false,
      imageLink: "img/black pawn.png",
    },
    {
      id: "black pawn b",
      type: "pawn",
      possison: "b7",
      color: "black",
      hasMoved: false,
      imageLink: "img/black pawn.png",
    },
    {
      id: "black pawn c",
      type: "pawn",
      possison: "c7",
      color: "black",
      hasMoved: false,
      imageLink: "img/black pawn.png",
    },
    {
      id: "black pawn d",
      type: "pawn",
      possison: "d7",
      color: "black",
      hasMoved: false,
      imageLink: "img/black pawn.png",
    },
    {
      id: "black pawn e",
      type: "pawn",
      possison: "e7",
      color: "black",
      hasMoved: false,
      imageLink: "img/black pawn.png",
    },
    {
      id: "black pawn f",
      type: "pawn",
      possison: "f7",
      color: "black",
      hasMoved: false,
      imageLink: "img/black pawn.png",
    },
    {
      id: "black pawn g",
      type: "pawn",
      possison: "g7",
      color: "black",
      hasMoved: false,
      imageLink: "img/black pawn.png",
    },
    {
      id: "black pawn h",
      type: "pawn",
      possison: "h7",
      color: "black",
      hasMoved: false,
      imageLink: "img/black pawn.png",
    },
    {
      id: "white king e",
      type: "king",
      possison: "e1",
      color: "white",
      hasMoved: false,
      imageLink: "img/white king.png",
    },
    {
      id: "white queen d",
      type: "queen",
      possison: "d1",
      color: "white",
      imageLink: "img/white queen.png",
    },
    {
      id: "white bishop c",
      type: "bishop",
      possison: "c1",
      color: "white",
      imageLink: "img/white bishop.png",
    },
    {
      id: "white bishop f",
      type: "bishop",
      possison: "f1",
      color: "white",
      imageLink: "img/white bishop.png",
    },
    {
      id: "white knight b",
      type: "knight",
      possison: "b1",
      color: "white",
      imageLink: "img/white horse.png",
    },
    {
      id: "white knight g",
      type: "knight",
      possison: "g1",
      color: "white",
      imageLink: "img/white horse.png",
    },
    {
      id: "white rook a",
      type: "rook",
      possison: "a1",
      color: "white",
      hasMoved: false,
      imageLink: "img/white rook.png",
    },
    {
      id: "white rook h",
      type: "rook",
      possison: "h1",
      color: "white",
      hasMoved: false,
      imageLink: "img/white rook.png",
    },
    {
      id: "white pawn a",
      type: "pawn",
      possison: "a2",
      color: "white",
      hasMoved: false,
      imageLink: "img/white pawn.png",
    },
    {
      id: "white pawn b",
      type: "pawn",
      possison: "b2",
      color: "white",
      hasMoved: false,
      imageLink: "img/white pawn.png",
    },
    {
      id: "white pawn c",
      type: "pawn",
      possison: "c2",
      color: "white",
      hasMoved: false,
      imageLink: "img/white pawn.png",
    },
    {
      id: "white pawn d",
      type: "pawn",
      possison: "d2",
      color: "white",
      hasMoved: false,
      imageLink: "img/white pawn.png",
    },
    {
      id: "white pawn e",
      type: "pawn",
      possison: "e2",
      color: "white",
      hasMoved: false,
      imageLink: "img/white pawn.png",
    },
    {
      id: "white pawn f",
      type: "pawn",
      type: "pawn",
      possison: "f2",
      color: "white",
      hasMoved: false,
      imageLink: "img/white pawn.png",
    },
    {
      id: "white pawn g",
      type: "pawn",
      possison: "g2",
      color: "white",
      hasMoved: false,
      imageLink: "img/white pawn.png",
    },
    {
      id: "white pawn h",
      type: "pawn",
      possison: "h2",
      color: "white",
      hasMoved: false,
      imageLink: "img/white pawn.png",
    },
  ],
};
